# Generated by Django 2.1.15 on 2022-11-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0009_auto_20221127_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='slug',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
