# Generated by Django 2.1.15 on 2022-11-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_auto_20221127_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
