# Generated by Django 2.1.15 on 2022-11-27 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_remove_cartitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
