# Generated by Django 2.1.15 on 2022-11-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0017_auto_20221129_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
