# Generated by Django 2.1.15 on 2022-11-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0018_auto_20221129_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='slug',
        ),
    ]
