# Generated by Django 2.1.15 on 2022-11-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_auto_20221130_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
