# Generated by Django 2.1.15 on 2022-11-30 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0021_auto_20221130_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
