# Generated by Django 2.1.15 on 2022-11-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0022_auto_20221130_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
