# Generated by Django 2.1.15 on 2022-12-06 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0025_auto_20221206_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
