# Generated by Django 2.1.15 on 2022-12-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0027_auto_20221206_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
