# Generated by Django 2.1.15 on 2022-12-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0028_auto_20221206_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
