# Generated by Django 2.1.15 on 2022-11-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('computers', 'COMPUTERS'), ('mobile', 'MOBILES'), ('tvs', 'TVs'), ('cameras', 'CAMERAS'), ('speakers', 'SPEAKERS')], default='computers', max_length=5),
        ),
    ]
