# Generated by Django 2.1.15 on 2022-11-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221126_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('computers', 'COMPUTERS'), ('mobile', 'MOBILES'), ('tvs', 'TVs'), ('cameras', 'CAMERAS'), ('speakers', 'SPEAKERS')], default='computers', max_length=10),
        ),
    ]
