# Generated by Django 2.1.15 on 2022-11-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221126_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='category_name',
        ),
    ]
