# Generated by Django 2.1.15 on 2022-12-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20221126_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('COMPUTERS', 'computers'), ('MOBILES', 'mobiles'), ('TVs', 'tvs'), ('CAMERAS', 'cameras'), ('SPEAKERS', 'speakers')], default='COMPUTERS', max_length=10),
        ),
    ]
