# Generated by Django 2.1.15 on 2022-12-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20221207_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('computers', 'COMPUTERS'), ('mobile', 'MOBILES'), ('tvs', 'TVs'), ('cameras', 'CAMERAS'), ('speakers', 'SPEAKERS')], default='computers', max_length=10),
        ),
    ]
