# Generated by Django 2.1.15 on 2022-12-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20221207_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducttimestamp',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproducttimestamp',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProductTimestamp',
        ),
    ]
